### ISSUE TITLE
Use my own UI

### ISSUE THREAD

**Issue by YazanAlaynin1** [ahmedelkhyary/hyperpay#5]
Can you please explain more if we can use our own UI and add example for that?

**Comment by ahmedelkhyary** [comment]
We will implement it, but not at the moment
You can go to the official website about custom ui.

**Comment by Mo-Meshrif** [comment]
Thank you for your effort to make this excellent library. I tried it and it works without problems or complications in the test mode, but I encountered some issues when converting to the live mode, which is as follows:
1-when entering the checkout id which I get it from live prepare checkout Api, the payment form doesn't create.
2-Although I have selected live mode when entering the checkout id which I get it from test prepare checkout API, the payment form created.
In the end, I realized that the library works in test mode, even if I select live mode. I think it may be because "com.testpayment.payment" or another reason causes those issues.
